name: anchore-grype-scanning
on: [push]
jobs:
  anchore_scan_job:
    runs-on: ubuntu-latest
    name: Anchore grype code security scan
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Scan current project
      id: scan
      uses: anchore/scan-action@v2
      with:
        path: "."
        fail-build: false
        acs-report-enable: true
        severity-cutoff: critical
    
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
        
    - name: Build the container image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      
    - name: Scan the container image
      uses: anchore/scan-action@v3
      with:
        image: "localbuild/testimage:latest"
        fail-build: true
    
