name: anchore-grype-scanning
on: [push]
jobs:
  anchore_scan_job:
    runs-on: ubuntu-latest
    name: Anchore grype security scan
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Scan current project
      id: scan
      uses: anchore/scan-action@v2
      with:
        path: "."
        fail-build: true
        acs-report-enable: true
        severity-cutoff: critical
    
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: build local container
      uses: docker/build-push-action@v2
      with:
        tags: devops-counsel/anchore-demo:latest
        push: false
        load: true

    - name: Scan image
      uses: anchore/scan-action@v3
      id: imagescan
      with:
        image: "devops-counsel/anchore-demo:latest"
        acs-report-enable: "true"
        severity-cutoff: critical
        fail-build: false

    - name: upload Anchore Image scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.imagescan.outputs.sarif }}
